apiVersion: v1
kind: Service
metadata:
  name: games
  namespace: alpha-apps
  labels:
    env: dev
spec:
  selector:
    app: games
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: games
  namespace: alpha-apps
  labels:
    app: games
    env: dev
spec:
  replicas: 3
  selector:
    matchLabels:
      app: games
      env: dev
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: games
        env: dev
    spec:
      serviceAccountName: docker-registry
      containers:
        - name: games
          image: smuralee/games-api:50a7165
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
              protocol: TCP
          livenessProbe:
            httpGet:
              port: 8080
              path: /games
            initialDelaySeconds: 60
          resources:
            requests:
              memory: "512Mi"
              cpu: "512m"
            limits:
              memory: "1024Mi"
              cpu: "1024m"


